### ISSUE TITLE
Exporting to .eeg crashes with annotations

### ISSUE THREAD

**Issue by cbrnr** [cbrnr/mnelab#104]
An MNELAB user reported that the app crashes when creating some annotations and then exporting to BrainVision format.

```
Used Annotations descriptions: ['1', '2', '3', '4', '8']
Traceback (most recent call last):
  File "C:\Python\Anaconda\envs\mnelab\lib\site-packages\mnelab\mainwindow.py", line 431, in export_file
    f(fname, ffilter)
  File "C:\Python\Anaconda\envs\mnelab\lib\site-packages\mnelab\model.py", line 253, in export_data
    self._export_bv(fname)
  File "C:\Python\Anaconda\envs\mnelab\lib\site-packages\mnelab\model.py", line 340, in _export_bv
    events = np.column_stack([events[:, [0, 2]], dur.astype(int)])
  File "<__array_function__ internals>", line 6, in column_stack
  File "C:\Python\Anaconda\envs\mnelab\lib\site-packages\numpy\lib\shape_base.py", line 641, in column_stack
    return _nx.concatenate(arrays, 1)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 90 and the array at index 1 has size 93
```

**Comment by cbrnr** [comment]
This seems to be related to the changed default behavior of `mne.events_from_annotations()`, which now ignores annotations starting with `'bad'` or `'edge'`.

**Comment by cbrnr** [comment]
@sappelhoff maybe you can help me here. I am converting annotations to events using `mne.events_from_annotations(raw, regexp=None)` to avoid dropping `bad` and `edge` annotations. However, this gives me an event type of `1`, which gets mapped to `Stimulus/S  1`, which is not what I want. Do you know how to create a proper event type that gets mapped to some sort of "bad segment" description by `write_brainvision()`?

**Comment by sappelhoff** [comment]
We need to fix it in pybv, I think: event writing is very limited there currently (see the issue you already commented on)

**Comment by cbrnr** [comment]
I see, thanks for the quick reply. Then I'll fix it in MNELAB so that at least it works somehow, and the correct marker type will be tackled in pybv later.
