### ISSUE TITLE
Add syntax check to history

### ISSUE THREAD

**Issue by hofaflo** [cbrnr/mnelab#306]
During development, it would be convenient if the history was checked for syntax errors. This can be implemented with the built-in function [`compile`](https://docs.python.org/3/library/functions.html#compile). Here's a basic example for this function:
```
>>> compile("a = 1\n b=2", "history", "exec")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "history", line 2
    b=2
IndentationError: unexpected indent
```

**Comment by cbrnr** [comment]
Could this be a test then?
