### ISSUE TITLE
error when installing: No such file or directory: '/System/Library/CoreServices/SystemVersion.plist'

### ISSUE THREAD

**Issue by danieltomasz** [cbrnr/mnelab#94]
when updating to 5.0 on Ubuntu 18.04 and python3.6
```
   ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-543k_rpn/pyobjc-framework-Cocoa/setup.py'"'"'; __file__='"'"'/tmp/pip-install-543k_rpn/pyobjc-framework-Cocoa/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-543k_rpn/pyobjc-framework-Cocoa/pip-egg-info
         cwd: /tmp/pip-install-543k_rpn/pyobjc-framework-Cocoa/
    Complete output (15 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-543k_rpn/pyobjc-framework-Cocoa/setup.py", line 25, in <module>
        extra_link_args=["-framework", "CoreFoundation"],
      File "/tmp/pip-install-543k_rpn/pyobjc-framework-Cocoa/pyobjc_setup.py", line 408, in Extension
        os_level = get_os_level()
      File "/tmp/pip-install-543k_rpn/pyobjc-framework-Cocoa/pyobjc_setup.py", line 218, in get_os_level
        pl = plistlib.readPlist("/System/Library/CoreServices/SystemVersion.plist")
      File "/usr/lib/python3.6/plistlib.py", line 162, in readPlist
        with _maybe_open(pathOrFile, 'rb') as fp:
      File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/usr/lib/python3.6/plistlib.py", line 120, in _maybe_open
        with open(pathOrFile, mode) as fp:
    FileNotFoundError: [Errno 2] No such file or directory: '/System/Library/CoreServices/SystemVersion.plist'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

``

**Comment by cbrnr** [comment]
I'm assuming you did `pip install -U mnelab`, correct?

**Comment by cbrnr** [comment]
Fixed in v0.5.1 - please try installing now, I've tested this on my Linux machine and it works.

**Comment by danieltomasz** [comment]
It works!

**Comment by cbrnr** [comment]
Nice, thanks for reporting this!
